# Generated by Django 4.2.1 on 2023-05-24 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='zip_code',
            new_name='zip',
        ),
    ]
