# Generated by Django 4.2.1 on 2023-05-24 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0002_rename_zip_code_location_zip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='truck',
            old_name='current_location',
            new_name='location',
        ),
    ]
