# Generated by Django 4.2.1 on 2023-05-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0003_rename_current_location_truck_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='zip',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='truck',
            name='unique_number',
            field=models.CharField(max_length=6),
        ),
    ]
