# Generated by Django 4.2.1 on 2023-05-24 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0005_cargo_truck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='truck',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='delivery_app.truck'),
        ),
    ]
